### ISSUE TITLE
EKS 환경에서 MicroVM을 사용할 수 있도록 Custom AMI 제작.

### ISSUE THREAD

**Issue by MoohyunSong** [ddps-lab/Callisto#3]
EKS 환경에서 Firecracker MicroVM을 통해 Container를 구동하기 위해서는 아래와 같은 작업이 필요합니다.

- Kubernetes에 Container Runtime 등록
  - 아래는 gVisor 예시입니다. (Firecracker에 맞게 수정 필요)
   ```bash
    cat <<EOF | kubectl apply -f -
    apiVersion: node.k8s.io/v1
    kind: RuntimeClass
    metadata:
      name: gvisor
    handler: runsc
    EOF 
    ```
- Worker Node에 해당 Container Runtime이 설치되어있어야함.
  - Worker Node Containerd의 설정을 변경해서 AMI를 생성해야 합니다.
  - 아래와 같은 내용을 참고해서 Firecracker에 맞게 추가해야 합니다. (아래는 기본 runtime인 runc에 추가적으로 runsc (gvisor)를 추가하는 예제)
    ```bash
    cat <<EOF | sudo tee /etc/containerd/config.toml
    version = 2
    [plugins."io.containerd.runtime.v1.linux"]
      shim_debug = true
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
      runtime_type = "io.containerd.runc.v2"
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runsc]
      runtime_type = "io.containerd.runsc.v1"
    EOF
     ```
- Karpenter에서 Custom AMi를 사용할 수 있도록 구성해야 함.
  - https://karpenter.sh/docs/tasks/managing-amis/
  - Karpenter Node Class 정의 시, 아래와 같은 방법으로 사용할 AMI를 지정해야 합니다.
    ```
    amiSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}"
        environment: prod
    - id: ami-052c9ea013e6e3567
    ```
